# Generated by Django 5.0 on 2025-08-19 12:33

import django.core.validators
import django.db.models.deletion
import dream_decoding.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDreamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_model_version', models.CharField(default='eeg_text_best', max_length=50)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('auto_process_uploads', models.BooleanField(default=True)),
                ('total_uploads', models.PositiveIntegerField(default=0)),
                ('successful_analyses', models.PositiveIntegerField(default=0)),
                ('total_processing_time', models.DurationField(blank=True, null=True)),
                ('favorite_dream_themes', models.JSONField(blank=True, default=list)),
                ('dream_journal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dream_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_dream_profiles',
            },
        ),
        migrations.CreateModel(
            name='EEGPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('eeg_file', models.FileField(help_text='Upload EEG .edf files only', upload_to=dream_decoding.models.eeg_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['edf', 'EDF'])])),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploaded', 'File Uploaded'), ('processing', 'Processing'), ('completed', 'Completed Successfully'), ('failed', 'Processing Failed')], default='pending', max_length=20)),
                ('dream_description', models.TextField(blank=True, help_text='Generated dream text', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Model confidence (0-1)', null=True)),
                ('detected_sleep_stage', models.IntegerField(blank=True, choices=[(0, 'Wake'), (1, 'Light Sleep (N1)'), (2, 'Deep Sleep (N2)'), (3, 'Deep Sleep (N3)'), (4, 'REM Sleep')], null=True)),
                ('num_windows_processed', models.PositiveIntegerField(default=0)),
                ('num_dream_segments', models.PositiveIntegerField(default=0)),
                ('model_version', models.CharField(default='eeg_text_best_v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.DurationField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
                ('eeg_metadata', models.JSONField(blank=True, default=dict)),
                ('analysis_metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dream_predictions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dream_predi_user_id_81aa51_idx'), models.Index(fields=['processing_status'], name='dream_predi_process_c6ab55_idx'), models.Index(fields=['created_at'], name='dream_predi_created_0ae672_idx')],
            },
        ),
    ]
