# Generated by Django 5.0 on 2025-08-21 11:06

import django.db.models.deletion
import dream_decoding.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_decoding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_text', models.TextField()),
                ('model_used', models.CharField(default='placeholder-generator', max_length=100)),
                ('status', models.CharField(default='generated', max_length=20)),
                ('image', models.ImageField(upload_to=dream_decoding.models.dream_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dream_decoding.eegprediction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dream_images',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dream_image_user_id_86902e_idx'), models.Index(fields=['prediction', '-created_at'], name='dream_image_predict_e683cb_idx')],
            },
        ),
    ]
